apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-test-application
spec:
  selector:
    matchLabels:
      app: argo-test-application
  replicas: 2
  template:
    metadata:
      labels:
        app: argo-test-application
    spec:
      containers:
      - name: argo-test-application
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080

